# Logistic Regression

### Tutorials + Resources

* https://www.coursera.org/learn/machine-learning/resources/Zi29t
* 

### Imports

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import colors
import pylab

DATA_DIR='data/'

### Load Data

In [3]:
def load_data(filepath):
    return np.loadtxt(filepath, skiprows=1, delimiter=",", usecols=(1,2,3,4))

data = load_data(DATA_DIR+'Advertising.csv')
print "Data Shape: "+str(data.shape)

#Features are TV, Radio, Newspaper
#The last column is Sales (y)
features = data[:,[0,1,2]]
targets = data[:,3]
targets.shape = (200,1) #reshape to keep consistent w features

print "Features shape: "+str(features.shape)
print features[:3]
print "Targets shape: "+str(targets.shape)
print targets[:3]

Data Shape: (200, 4)
Features shape: (200, 3)
[[ 230.1   37.8   69.2]
 [  44.5   39.3   45.1]
 [  17.2   45.9   69.3]]
Targets shape: (200, 1)
[[ 22.1]
 [ 10.4]
 [  9.3]]
