# Titanic

Based on the titanic tutorial here: https://www.kaggle.com/c/titanic/details/getting-started-with-python

In [65]:
# The first thing to do is to import the relevant packages
# that I will need for my script, 
# these include the Numpy (for maths and arrays)
# and csv for reading and writing csv files
# If i want to use something from this I need to call 
# csv.[function] or np.[function] first

import csv as csv 
import numpy as np

# Open up the csv file in to a Python object
csv_file_object = csv.reader(open('data/train.csv', 'rb')) 

headers = csv_file_object.next()
data = []                        # Create a variable called 'data'.
for row in csv_file_object:      # Run through each row in the csv file,
    data.append(row)             # adding each row to the data variable
data = np.array(data)            # Then convert from a list to an array
                                 # Be aware that each item is currently
                                 # a string in this format

In [66]:
print headers
print data[0]
print data[0,3]    #print 4th column in 1st row

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
['1' '0' '3' 'Braund, Mr. Owen Harris' 'male' '22' '1' '0' 'A/5 21171'
 '7.25' '' 'S']
Braund, Mr. Owen Harris


In [67]:
vals = data[0::,1]     #get all values in the 2nd column
print data[0::,1].astype(np.int)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [68]:
# The size() function counts how many elements are in
# in the array and sum() (as you would expects) sums up
# the elements in the array.

number_passengers = np.size(data[0::,1].astype(np.float))
number_survived = np.sum(data[0::,1].astype(np.float))
proportion_survivors = number_survived / number_passengers

In [69]:
print number_passengers
print number_survived
print proportion_survivors

891
342.0
0.383838383838


Numpy functions

In [70]:
women_only_stats = data[0::,4] == "female" #Returns True if val in 5th column is female
men_only_stats = data[0::,4] != "female"

print women_only_stats
print men_only_stats

[False  True  True  True False False False False  True  True  True  True
 False False  True  True False False  True  True False False  True False
  True  True False False  True False False  True  True False False False
 False False  True  True  True  True False  True  True False False  True
 False  True False False  True  True False False  True False  True False
 False  True False False False False  True False  True False False  True
 False False False False False False False  True False False  True False
  True  True False False  True False False False False False False False
 False False  True False  True False False False False False  True False
 False  True False  True False  True  True False False False False  True
 False False False  True False False False False  True False False False
  True  True False False  True False False False  True  True  True False
 False False False  True False False False  True False False False False
  True False False False False  True False False Fa

We use these two new variables as a "mask" on our original train data, so we can select only those women, and only those men on board, then calculate the proportion of those who survived:

In [71]:
# Using the index from above we select the females and males separately
women_onboard = data[women_only_stats,1].astype(np.float)     #index 1 = survival rate
men_onboard = data[men_only_stats,1].astype(np.float)

print len(women_onboard)
print len(men_onboard)

# Then we finds the proportions of them that survived
proportion_women_survived = \
                       np.sum(women_onboard) / np.size(women_onboard)  
proportion_men_survived = \
                       np.sum(men_onboard) / np.size(men_onboard) 

# and then print it out
print 'Proportion of women who survived is %s' % proportion_women_survived
print 'Proportion of men who survived is %s' % proportion_men_survived

314
577
Proportion of women who survived is 0.742038216561
Proportion of men who survived is 0.188908145581


### Start making predictions!

In [72]:
test_file = open('data/test.csv', 'rb')
test_file_object = csv.reader(test_file)
header = test_file_object.next()

prediction_file = open("data/genderclasspredictions.csv", "wb")
prediction_file_object = csv.writer(prediction_file)

### Normalize Data w Bins

In [73]:
# In order to analyse the price column I need to bin up that data
# here are my binning parameters, the problem we face is some of the fares are very large
# So we can either have a lot of bins with nothing in them or we can just lose some
# information by just considering that anythng over 39 is simply in the last bin.
# So we add a ceiling
fare_ceiling = 40
# then modify the data in the Fare column to = 39, if it is greater or equal to the ceiling
data[ data[0::,9].astype(np.float) >= fare_ceiling, 9 ] = fare_ceiling - 1.0

fare_bracket_size = 10
number_of_price_brackets = fare_ceiling / fare_bracket_size
number_of_classes = 3                             # I know there were 1st, 2nd and 3rd classes on board.
number_of_classes = len(np.unique(data[0::,2]))   # But it's better practice to calculate this from the Pclass directly:
                                                  # just take the length of an array of UNIQUE values in column index 2

### Creating a Survival Reference Table

In [74]:
# This reference matrix will show the proportion of survivors as a sorted table of
# gender, class and ticket fare.
# First initialize it with all zeros
survival_table = np.zeros([2,number_of_classes,number_of_price_brackets],float) #returns [nested [arrays]] of all 0s
print survival_table

# I can now find the stats of all the women and men on board
for i in xrange(number_of_classes):                                 #xrange uses generators + yield behind the scenes. Good for large data sets.
    for j in xrange(number_of_price_brackets):

        women_only_stats = data[ (data[0::,4] == "female") \
                                 & (data[0::,2].astype(np.float) == i+1) \
                                 & (data[0:,9].astype(np.float) >= j*fare_bracket_size) \
                                 & (data[0:,9].astype(np.float) < (j+1)*fare_bracket_size), 1]

        men_only_stats = data[ (data[0::,4] != "female") \
                                 & (data[0::,2].astype(np.float) == i+1) \
                                 & (data[0:,9].astype(np.float) >= j*fare_bracket_size) \
                                 & (data[0:,9].astype(np.float) < (j+1)*fare_bracket_size), 1]

                                 #if i == 0 and j == 3:

        survival_table[0,i,j] = np.mean(women_only_stats.astype(np.float))  # Female stats
        survival_table[1,i,j] = np.mean(men_only_stats.astype(np.float))    # Male stats

#They use an array, but a dictionary would be easier to read        
print "\nSurvival Reference Table We Use To Lookup a Passengers expected survival"
print survival_table

#Remove nan values
survival_table[ survival_table != survival_table ] = 0

print "\nRounding To Nearest Survival Rating: 0 or 1"
survival_table[ survival_table < 0.5 ] = 0
survival_table[ survival_table >= 0.5 ] = 1 
print survival_table

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]

Survival Reference Table We Use To Lookup a Passengers expected survival
[[[        nan         nan  0.83333333  0.97727273]
  [        nan  0.91428571  0.9         1.        ]
  [ 0.59375     0.58139535  0.33333333  0.125     ]]

 [[ 0.                 nan  0.4         0.38372093]
  [ 0.          0.15873016  0.16        0.21428571]
  [ 0.11153846  0.23684211  0.125       0.24      ]]]

Rounding To Nearest Survival Rating: 0 or 1
[[[ 0.  0.  1.  1.]
  [ 0.  1.  1.  1.]
  [ 1.  1.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


### Writing The Predictions File

In [78]:
test_file = open('data/test.csv', 'rb')
test_file_object = csv.reader(test_file)
header = test_file_object.next()
predictions_file = open("data/genderclasspredictions.csv", "wb")
p = csv.writer(predictions_file)
p.writerow(["PassengerId", "Survived"])

In [79]:
for row in test_file_object:                 # We are going to loop
                                              # through each passenger
                                              # in the test set                     
    #FIND THE RIGHT FARE BIN
    for j in xrange(number_of_price_brackets):  # For each passenger we
                                                  # loop thro each price bin
        try:                                      # Some passengers have no
                                                  # Fare data so try to make
          row[8] = float(row[8])                  # a float
        except:                                   # If fails: no data, so 
          bin_fare = 3 - float(row[1])            # bin the fare according Pclass
          break                                   # Break from the loop
        if row[8] > fare_ceiling:              # If there is data see if
                                                  # it is greater than fare
                                                  # ceiling we set earlier
          bin_fare = number_of_price_brackets-1   # If so set to highest bin
          break                                   # And then break loop
        if row[8] >= j * fare_bracket_size\
           and row[8] < \
           (j+1) * fare_bracket_size:             # If passed these tests 
                                                  # then loop through each bin 
          bin_fare = j                            # then assign index
          break
    
    #USE THE LOOKUP TABLE
    if row[3] == 'female':                             #If the passenger is female
        p.writerow([row[0], "%d" % \
            int(survival_table[0, float(row[1])-1, bin_fare])])
    else:                                          #else if male
        p.writerow([row[0], "%d" % \
            int(survival_table[1, float(row[1])-1, bin_fare])])

# Close out the files.
test_file.close() 
predictions_file.close()

/Users/Brendan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:27: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
/Users/Brendan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:25: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
